Add usage of i18n for plugins manager
CzBiX/qb-web pull request #61
Opened 2020-09-24 07:32 UTC by bbogdanov

Forgot to use i18n for the labels

2020-09-24 08:24 UTC, CzBiX requested changes

2020-09-24 08:24 UTC, CzBiX commented on src/components/dialogs/searchDialog/PluginsManager.vue
> +      <v-card-title> <v-icon>mdi-toy-brick</v-icon> {{ $t("plugin", 1) }} {{ $t("manager") }} </v-card-title>
can be one label

2020-09-24 08:24 UTC, CzBiX commented on src/components/dialogs/searchDialog/SearchDialog.vue
> +            <v-icon>mdi-cog</v-icon> {{ $t("plugin", 1) }} {{ $t("manager") }}
also

2020-09-24 08:24 UTC, CzBiX commented on src/locale/en.ts
> +  manager: 'manager',
also

2020-09-25 05:55 UTC, bbogdanov commented
@CzBiX Do not forget to squash

2020-09-25 08:12 UTC, merged